movietime:
  app:
    mode: DEV
    version: ${pom.version}
    apiVersion: v1
    responseFormat: application/json;utf-8
    bugSnag: 16f3943bcff62960d25dcf14053efb98
    taskPool:
      corePoolSize: 5
      maxPoolSize: 10
      queueCapacity: 25
    tasks: #See TaskEnum
      - 
        name: THEATER_UPDATE
        cron: '0 0 20 * * WED'
      -
        name: SHOWTIME_UPDATE
        cron: '0 0 23 * * WED,SUN'
      -
        name: MOVIE_COMING_SOON
        cron: '0 0 22 * * SUN'
      -
        name: MOVIE_RATING_UPDATE
        cron: '0 0 22 * * SUN'
      -
        name: MOVIE_INFORMATION_UPDATE
        cron: '0 0 22 * * SUN'
  mongo:
    url: mongodb://localhost/hellocinedb
    writeResultChecking: EXCEPTION   #NONE, LOG, EXCEPTION
  graphite:
    activate: false
    apiKey: c68abc3f-0356-4f5e-a0c3-062db5ae697b
    host: carbon.hostedgraphite.com
    port: 2003
  client:
    readTimeOut: 20000
    connectTimeout: 5000
    activateMetrics: true
    userAgent: Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5

error:
  whitelabel:
    enabled: false
health:
  mongodb:
    enabled: false
management:
  #port: -1 #ucomment to disable
  context-path: /manage
  security:
    role: MANAGER
info:
  build:
   artifact: ${project.artifactId}
   name: ${project.name}
   description: ${project.description}
   version: ${project.version}
endpoints:
  info:
    sensitive: true
  health:
    sensitive: true
#security:
#  user:
#    name: super
#    password: secret
#    role: SUPERUSER