app:
  mode: DEV
  version: ${pom.version}
  mongoUrl: mongodb://localhost/hellocinedb
  bugSnag: 16f3943bcff62960d25dcf14053efb98
  client:
    readTimeOut: 5000
    connectTimeout: 2000
    userAgent: Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5
endpoints:
  beans:
    id: beans
    sensitive: false
    enabled: true
  jolokia:
    enabled: true
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
security:
  user:
    name: admin
    password: secret
management:
  security:
    role: SUPERUSER
  context-path: /manage
jolokia:
  config:
    debug: true