movietime:
  app:
    mode: TEST
    enableSecurity: false
  mongo:
    url: mongodb://localhost/test
    writeResultChecking: EXCEPTION
  graphite:
      activate: false
  client:
    activateMetrics: false
